# SwiftLint 配置文件
# 参考: https://github.com/realm/SwiftLint

# 禁用规则
disabled_rules:
  - trailing_whitespace
  - todo
  
# 选择性启用规则
opt_in_rules:
  - empty_count
  - force_unwrapping
  - implicitly_unwrapped_optional
  - closure_spacing
  - contains_over_first_not_nil
  - explicit_init
  - fatal_error_message
  - first_where
  - modifier_order
  - operator_usage_whitespace
  - overridden_super_call
  - prohibited_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# 排除路径
excluded:
  - Pods
  - Carthage
  - DerivedData
  - ios/EarWordsTests
  - ios/EarWordsUITests
  - ios/EarWordsWidgets
  - data

# 行长度限制
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: false
  ignores_comments: true

# 函数体长度
function_body_length:
  warning: 50
  error: 100

# 文件长度
file_length:
  warning: 500
  error: 1000

# 类型体长度
type_body_length:
  warning: 300
  error: 500

# 函数参数数量
function_parameter_count:
  warning: 5
  error: 8

# 标识符命名
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
    - n
    - ok
    - url
    - url
    - url
    - URL
  allowed_symbols:
    - "_"

# 类型命名
type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - ID
    - URL

# 变量声明间距
vertical_whitespace:
  max_empty_lines: 2

# 圈复杂度
cyclomatic_complexity:
  warning: 10
  error: 20

# 嵌套深度
nesting:
  type_level:
    warning: 2
    error: 4
  statement_level:
    warning: 5
    error: 10

# 控制语句
control_statement:
  severity: warning

# 隐式返回
implicit_return:
  included:
    - closure
    - getter

# 强制类型转换
force_cast: error
force_try: warning

# 弃用代码
discarded_notification_center_observer: warning
notification_center_detachment: warning

# 冒号规则
colon:
  severity: warning
  apply_to_dictionaries: true

# 逗号规则
comma:
  severity: warning

# 括号规则
opening_brace:
  severity: warning

closing_brace:
  severity: warning

# 空父类
empty_parentheses_with_trailing_closure: warning

# 尾随闭包
trailing_closure:
  severity: warning
  only_single_muted_parameter: true

# 运算符重载
operator_whitespace:
  severity: warning

# 返回箭头
return_arrow_whitespace:
  severity: warning

# 语句位置
statement_position:
  severity: warning

# 多余分号
trailing_semicolon:
  severity: warning

# 尾随换行
trailing_newline:
  severity: warning

# 自定义规则
custom_rules:
  no_print:
    name: "No Print"
    regex: "print\\("
    message: "请使用日志框架替代 print"
    severity: warning
  
  no_nslog:
    name: "No NSLog"
    regex: "NSLog\\("
    message: "请使用日志框架替代 NSLog"
    severity: error
  
  no_force_unwrap:
    name: "No Force Unwrap"
    regex: "\\!\\s*(?:$|[;,])"
    message: "避免使用强制解包"
    severity: warning
    excluded:
      - ".*Tests.*"
      - ".*Test.*"
  
  no_fatal_error:
    name: "No Fatal Error"
    regex: "fatalError\\("
    message: "避免在生产代码中使用 fatalError"
    severity: warning
    excluded:
      - ".*Tests.*"
      - ".*Test.*"
